### ISSUE TITLE
Cannot run S1Processor

### ISSUE THREAD

**Issue by rkanavath** [CNES/S1Tiling#1]
https://github.com/CNES/S1Tiling/blob/master/S1Processor.py#L225

the code tries to open a image using gdal
```raster = gdal.Open(image)```

and image is set to 
```
image=raw_raster[i][0].get_images_list()[0]
image = image.replace(".tiff","_calOk.tiff")
```
"_calOk.tiff" image does not exists in the S1 product downloaded from sentinel hub

product id:  S1A_IW_GRDH_1SDV_20200208T060054_20200208T060119_031157_0394F3_B75C.SAFE

BackTrace:
```
  File "/work/S1Tiling/S1Processor.py", line 657, in <module>
    S1_CHAIN.cut_image_cmd(intersect_raster_list)
  File "/work/S1Tiling/S1Processor.py", line 228, in cut_image_cmd
    xsize = raster.RasterXSize
AttributeError: 'NoneType' object has no attribute 'RasterXSize'
```

**Comment by rkanavath** [comment]
replacing run_processing method with below code and removing all export ITK_... in the command string make the processing chain move a little bit.
```
    def run_processing(self, cmd_list, title=""):
        """
        This method executes a given command.
        Args:
          cmd_list: the command to run
          title: optional title
        """
        for cmd in cmd_list:
            execute(cmd)
        return
```

But overall the code quality is below average  and is not fixable other than rewrite/start-from-scratch strategy. This is somewhat equivalent of bash to python auto code translation.

**Comment by TristanGaudin** [comment]
Hello @rkanavath 

I have the same error than you : 

`Traceback (most recent call last):
  File "/media/kermap/45c64895-f8e0-41aa-b396-a40592f7a05d/Images_Radar/Mosaique_S1/France/S1_tiling/S1Processor.py", line 596, in <module>
    S1_CHAIN.cut_image_cmd(intersect_raster_list)
  File "/media/kermap/45c64895-f8e0-41aa-b396-a40592f7a05d/Images_Radar/Mosaique_S1/France/S1_tiling/S1Processor.py", line 221, in cut_image_cmd
    xsize = raster.RasterXSize
AttributeError: 'NoneType' object has no attribute 'RasterXSize'
`

I tried to do as you said before : replacing run_processing method with our code and removing all export ITK but the error is still there...

Do you have another solution? What version of GDAL do you use? 

For me, i'm trying with python3 and GDAL 2.4.2 on Linux system.

**Comment by LucHermitte** [comment]
Hi.

Just to let you know that S1Tiling as been refactored and it's maintained at https://gitlab.orfeo-toolbox.org/s1-tiling/s1tiling. As v0.2rc2 is available on pipy.

The issue you have observed should have been fixed. Let us know if this is not the case.

Note: The current repository on github will act as a mirror.
